### File code này để tính ra điểm RFM của từng khách hàng và lưu vào file `rfm.csv`

In [66]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [67]:
dft = pd.read_excel("DATA SET - VÒNG 1 CUỘC THI DATA GOT TALENT 2023.xlsx", sheet_name="ticket")
print(dft.info())
dft.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35474 entries, 0 to 35473
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   orderid       35378 non-null  object
 1   cashier       35474 non-null  object
 2   saledate      35378 non-null  datetime64[ns]
 3   total         35378 non-null  float64
 4   customerid    35474 non-null  object
 5   ticketcode    35474 non-null  int64
 6   date          35474 non-null  datetime64[ns]
 7   time          35474 non-null  object
 8   slot          35474 non-null  object
 9   room          35474 non-null  int64
 10  film          35474 non-null  object
 11  slot type     35474 non-null  object
 12  ticket type   35474 non-null  object
 13  ticket price  35474 non-null  int64
 14  popcorn       35378 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(3), object(9)
memory usage: 4.1+ MB
None

,orderid,cashier,saledate,total,customerid,ticketcode,date,time,slot,room,film,slot type,ticket type,ticket price,popcorn
0,10006052019B0225,emp002,2019-05-06 16:40:43,90000.0,0000000014,20074925,2019-05-06,18:15:00,G04,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
1,10006052019B0225,emp002,2019-05-06 16:40:43,90000.0,0000000014,20074924,2019-05-06,18:15:00,G03,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
2,10022052019B0167,emp011,2019-05-22 20:30:28,90000.0,0000000034,20097042,2019-05-22,20:45:00,E04,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
3,10022052019B0167,emp011,2019-05-22 20:30:28,90000.0,0000000034,20097041,2019-05-22,20:45:00,E03,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
4,10130052019B0141,emp005,2019-05-30 19:28:44,90000.0,0000000034,20106761,2019-05-30,19:30:00,F04,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
5,10130052019B0141,emp005,2019-05-30 19:28:44,90000.0,0000000034,20106757,2019-05-30,19:30:00,F03,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
6,10122052019B0056,emp007,2019-05-22 19:26:43,90000.0,0000000051,20096948,2019-05-22,19:40:00,E11,4,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
7,10122052019B0056,emp007,2019-05-22 19:26:43,90000.0,0000000051,20096947,2019-05-22,19:40:00,E10,4,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
8,10105052019B0147,emp011,2019-05-05 13:49:48,90000.0,0000000081,20073028,2019-05-05,14:00:00,F14,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
9,10105052019B0147,emp011,2019-05-05 13:49:48,90000.0,0000000081,20073029,2019-05-05,14:00:00,F15,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
10,10105052019B0145,emp011,2019-05-05 13:48:21,90000.0,0000000081,20073018,2019-05-05,14:00:00,E03,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
11,10105052019B0145,emp011,2019-05-05 13:48:21,90000.0,0000000081,20073019,2019-05-05,14:00:00,E04,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
12,12506052019B0054,emp011,2019-05-06 20:23:52,90000.0,0000000098,20075481,2019-05-06,20:50:00,H03,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
13,12506052019B0054,emp011,2019-05-06 20:23:52,90000.0,0000000098,20075482,2019-05-06,20:50:00,H04,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
14,10025052019B0126,emp006,2019-05-25 13:17:35,90000.0,0000000098,20099938,2019-05-25,13:40:00,E10,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Không
15,10025052019B0126,emp006,2019-05-25 13:17:35,90000.0,0000000098,20099937,2019-05-25,13:40:00,E09,2,VÔ GIAN ĐẠO (C18),ĐƠN,Thành viên,45000,Không
16,10119052019B0033,emp011,2019-05-19 14:42:42,90000.0,0000000109,20093408,2019-05-19,15:00:00,D10,3,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
17,10119052019B0033,emp011,2019-05-19 14:42:42,90000.0,0000000109,20093407,2019-05-19,15:00:00,D09,3,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
18,10128052019B0149,emp005,2019-05-28 20:12:07,90000.0,0000000221.,20104879,2019-05-28,20:20:00,H09,2,NGÔI ĐỀN KỲ QUÁI (C18),ĐÔI,Thành viên,90000,Không
19,10115052019B0131,emp011,2019-05-15 22:57:09,135000.0,0000000221.,20088888,2019-05-15,22:40:00,G09,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
20,10115052019B0131,emp011,2019-05-15 22:57:09,135000.0,0000000221.,20088887,2019-05-15,22:40:00,G08,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
21,10115052019B0131,emp011,2019-05-15 22:57:09,135000.0,0000000221.,20088886,2019-05-15,22:40:00,G07,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
22,10115052019B0130,emp011,2019-05-15 22:45:18,90000.0,0000000221.,20088885,2019-05-15,22:30:00,J04,1,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,90000,Không
23,NaN,Website,NaT,NaN,0000000228,20100926,2019-05-25,19:45:00,G09,3,ALADDIN (PD) (G),ĐƠN,Thành viên,45000,NaN
24,NaN,Website,NaT,NaN,0000000228,20100927,2019-05-25,19:45:00,G10,3,ALADDIN (PD) (G),ĐƠN,Thành viên,45000,NaN
25,10129052019B0143,emp007,2019-05-29 18:11:29,90000.0,0000000229,20105497,2019-05-29,18:10:00,I13,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
26,10129052019B0143,emp007,2019-05-29 18:11:29,90000.0,0000000229,20105496,2019-05-29,18:10:00,I12,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
27,10105052019B0002,emp011,2019-05-05 09:13:12,90000.0,0000000229,20072245,2019-05-05,18:15:00,H10,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
28,10105052019B0002,emp011,2019-05-05 09:13:12,90000.0,0000000229,20072244,2019-05-05,18:15:00,H09,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
29,10005052019B0104,emp004,2019-05-05 11:04:00,90000.0,0000000266,20072572,2019-05-05,15:00:00,G07,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
30,10005052019B0104,emp004,2019-05-05 11:04:00,90000.0,0000000266,20072573,2019-05-05,15:00:00,G08,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
31,10030052019B0076,emp001,2019-05-30 12:25:05,90000.0,0000000268,20106087,2019-05-30,12:40:00,J05,1,NGÔI ĐỀN KỲ QUÁI (C18),ĐÔI,Thành viên,90000,Không
32,10117052019B0109,emp009,2019-05-17 19:07:40,90000.0,0000000285,20090917,2019-05-17,19:35:00,K07,4,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Không
33,10117052019B0109,emp009,2019-05-17 19:07:40,90000.0,0000000285,20090916,2019-05-17,19:35:00,K06,4,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Không
34,10110052019B0130,emp009,2019-05-10 16:40:23,90000.0,0000000297,20080271,2019-05-10,16:40:00,H03,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,90000,Không
35,10005052019B0031,emp004,2019-05-05 09:02:59,135000.0,0000000297,20072221,2019-05-05,15:00:00,E07,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
36,10005052019B0031,emp004,2019-05-05 09:02:59,135000.0,0000000297,20072223,2019-05-05,15:00:00,E09,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
37,10005052019B0031,emp004,2019-05-05 09:02:59,135000.0,0000000297,20072222,2019-05-05,15:00:00,E08,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
38,10026052019B0280,emp007,2019-05-26 18:01:00,90000.0,0000000309,20102308,2019-05-26,19:35:00,E10,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
39,10026052019B0280,emp007,2019-05-26 18:01:00,90000.0,0000000309,20102307,2019-05-26,19:35:00,E09,4,NGÔI ĐỀN KỲ QUÁI (C18),ĐƠN,Thành viên,45000,Không
40,10107052019B0026,emp011,2019-05-07 17:39:52,90000.0,0000000328,20076306,2019-05-07,19:15:00,F06,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
41,10107052019B0026,emp011,2019-05-07 17:39:52,90000.0,0000000328,20076305,2019-05-07,19:15:00,F05,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,45000,Không
42,10107052019B0027,emp011,2019-05-07 17:42:17,135000.0,0000000328,20076310,2019-05-07,19:00:00,I06,1,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Không
43,10107052019B0027,emp011,2019-05-07 17:42:17,135000.0,0000000328,20076308,2019-05-07,19:00:00,I04,1,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Không
44,10107052019B0027,emp011,2019-05-07 17:42:17,135000.0,0000000328,20076309,2019-05-07,19:00:00,I05,1,MẸ MA THAN KHÓC LA LLORONA (C18),ĐƠN,Thành viên,45000,Không
45,12521052019B0053,emp011,2019-05-21 20:48:54,90000.0,0000000328,20096336,2019-05-21,20:45:00,D03,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
46,12521052019B0053,emp011,2019-05-21 20:48:54,90000.0,0000000328,20096335,2019-05-21,20:45:00,D02,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
47,12521052019B0052,emp011,2019-05-21 20:46:12,45000.0,0000000328,20096332,2019-05-21,20:45:00,D01,2,JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18),ĐƠN,Thành viên,45000,Không
48,10110052019B0167,emp012,2019-05-10 17:54:47,90000.0,0000000375,20080431,2019-05-10,18:30:00,E11,2,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Không
49,10110052019B0167,emp012,2019-05-10 17:54:47,90000.0,0000000375,20080432,2019-05-10,18:30:00,E12,2,POKÉMON: THÁM TỬ PIKACHU (C13),ĐƠN,Thành viên,45000,Không

In [68]:
# Gộp các orderid trùng nhau
dft_clean = dft.groupby('orderid', as_index=False).agg(lambda x: x.unique()[0])

In [69]:
dft_clean.head(50)

,orderid,cashier,saledate,total,customerid,ticketcode,date,time,slot,room,film,slot type,ticket type,ticket price,popcorn
0,10001052019B0003,emp008,2019-05-01 07:05:53,160000.0,0000024994,20068404,2019-05-01,07:30:00,H05,2,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
1,10001052019B0004,emp008,2019-05-01 07:06:45,75000.0,0000024994,20068405,2019-05-01,07:30:00,E10,2,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
2,10001052019B0005,emp008,2019-05-01 07:15:58,225000.0,KH6166700,20068406,2019-05-01,08:45:00,G11,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
3,10001052019B0006,emp008,2019-05-01 07:17:28,150000.0,KH6166700,20068409,2019-05-01,07:30:00,E06,2,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
4,10001052019B0007,emp008,2019-05-01 07:26:28,160000.0,KH6166700,20068411,2019-05-01,07:30:00,H06,2,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
5,10001052019B0008,emp008,2019-05-01 07:31:20,225000.0,KH6166700,20068413,2019-05-01,15:15:00,I09,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
6,10001052019B0009,emp008,2019-05-01 07:35:18,225000.0,KH6166700,20068417,2019-05-01,08:45:00,I16,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
7,10001052019B0010,emp008,2019-05-01 07:37:03,150000.0,KH6166700,20068419,2019-05-01,07:30:00,F17,2,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
8,10001052019B0011,emp008,2019-05-01 07:37:30,75000.0,KH6166700,20068420,2019-05-01,07:30:00,F08,2,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
9,10001052019B0012,emp008,2019-05-01 07:46:40,450000.0,KH6166700,20068424,2019-05-01,08:45:00,G04,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
10,10001052019B0013,emp008,2019-05-01 07:49:07,150000.0,KH6166700,20068427,2019-05-01,08:45:00,E13,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
11,10001052019B0014,emp008,2019-05-01 07:54:12,150000.0,KH6166700,20068432,2019-05-01,18:30:00,I11,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
12,10001052019B0015,emp008,2019-05-01 07:55:07,150000.0,KH6166700,20068435,2019-05-01,10:15:00,E08,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
13,10001052019B0024,emp008,2019-05-01 08:16:55,150000.0,KH6166700,20068451,2019-05-01,08:45:00,E03,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
14,10001052019B0025,emp008,2019-05-01 08:20:41,150000.0,0001137446,20068453,2019-05-01,08:45:00,F02,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
15,10001052019B0026,emp008,2019-05-01 08:21:32,75000.0,0001137446,20068455,2019-05-01,08:45:00,I04,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
16,10001052019B0027,emp008,2019-05-01 08:22:30,150000.0,0001137446,20068457,2019-05-01,08:45:00,H07,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
17,10001052019B0028,emp008,2019-05-01 08:23:23,300000.0,0001137446,20068459,2019-05-01,08:45:00,F15,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
18,10001052019B0029,emp008,2019-05-01 08:24:29,150000.0,0001137446,20068462,2019-05-01,08:45:00,G16,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
19,10001052019B0030,emp008,2019-05-01 08:26:19,150000.0,0001137446,20068464,2019-05-01,08:45:00,E15,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
20,10001052019B0031,emp008,2019-05-01 08:28:11,160000.0,KH6166700,20068466,2019-05-01,08:45:00,J06,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
21,10001052019B0032,emp008,2019-05-01 08:30:16,600000.0,KH6166700,20068468,2019-05-01,13:30:00,E05,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
22,10001052019B0033,emp008,2019-05-01 08:31:06,75000.0,KH6166700,20068475,2019-05-01,13:30:00,E12,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
23,10001052019B0034,emp008,2019-05-01 08:34:15,160000.0,KH6166700,20068476,2019-05-01,08:45:00,J03,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
24,10001052019B0035,emp008,2019-05-01 08:36:07,300000.0,KH6166700,20068477,2019-05-01,08:45:00,D07,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
25,10001052019B0036,emp008,2019-05-01 08:37:20,150000.0,KH6166700,20068481,2019-05-01,08:45:00,E01,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
26,10001052019B0037,emp008,2019-05-01 08:38:16,160000.0,KH6166700,20068483,2019-05-01,08:45:00,J07,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
27,10001052019B0038,emp008,2019-05-01 08:39:13,75000.0,KH6166700,20068484,2019-05-01,19:15:00,E13,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
28,10001052019B0039,emp008,2019-05-01 08:40:44,160000.0,KH6166700,20068485,2019-05-01,17:20:00,H02,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,160000,Không
29,10001052019B0040,emp008,2019-05-01 08:41:56,225000.0,KH6166700,20068488,2019-05-01,08:45:00,H17,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
30,10001052019B0041,emp008,2019-05-01 08:43:51,150000.0,KH6166700,20068489,2019-05-01,19:15:00,G09,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
31,10001052019B0042,emp008,2019-05-01 08:44:50,160000.0,KH6166700,20068491,2019-05-01,10:45:00,H04,2,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
32,10001052019B0043,emp008,2019-05-01 08:49:25,160000.0,KH6166700,20068492,2019-05-01,08:45:00,J02,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
33,10001052019B0044,emp008,2019-05-01 08:50:00,160000.0,KH6166700,20068493,2019-05-01,14:05:00,H06,2,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
34,10001052019B0045,emp008,2019-05-01 08:51:56,150000.0,KH6166700,20068494,2019-05-01,10:15:00,I07,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
35,10001052019B0046,emp008,2019-05-01 08:52:33,225000.0,KH6166700,20068497,2019-05-01,08:45:00,I02,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
36,10001052019B0047,emp008,2019-05-01 08:53:56,160000.0,KH6166700,20068499,2019-05-01,15:15:00,J06,1,AVENGERS: HỒI KẾT,ĐÔI,Thành viên,160000,Không
37,10001052019B0048,emp008,2019-05-01 08:55:38,300000.0,KH6166700,20068502,2019-05-01,10:15:00,J09,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
38,10001052019B0049,emp008,2019-05-01 08:57:13,225000.0,KH6166700,20068505,2019-05-01,08:45:00,D12,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
39,10001052019B0050,emp008,2019-05-01 08:57:38,75000.0,KH6166700,20068507,2019-05-01,08:45:00,H05,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
40,10001052019B0051,emp008,2019-05-01 08:58:16,225000.0,KH6166700,20068510,2019-05-01,13:30:00,H11,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
41,10001052019B0052,emp008,2019-05-01 08:59:37,160000.0,KH6166700,20068511,2019-05-01,17:20:00,H04,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,160000,Không
42,10001052019B0053,emp008,2019-05-01 09:00:21,150000.0,KH6166700,20068512,2019-05-01,08:45:00,H01,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
43,10001052019B0054,emp008,2019-05-01 09:01:18,150000.0,KH6166700,20068514,2019-05-01,13:30:00,I09,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
44,10001052019B0056,emp008,2019-05-01 09:04:05,300000.0,KH6166700,20068521,2019-05-01,12:30:00,E08,3,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
45,10001052019B0057,emp008,2019-05-01 09:05:18,160000.0,KH6166700,20068524,2019-05-01,17:20:00,H07,2,MẸ MA THAN KHÓC LA LLORONA (C18),ĐÔI,Thành viên,160000,Không
46,10001052019B0058,emp008,2019-05-01 09:05:34,75000.0,KH6166700,20068527,2019-05-01,13:30:00,E03,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
47,10001052019B0059,emp008,2019-05-01 09:07:26,225000.0,KH6166700,20068532,2019-05-01,12:00:00,G08,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
48,10001052019B0060,emp008,2019-05-01 09:09:17,150000.0,KH6166700,20068538,2019-05-01,10:15:00,G04,4,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không
49,10001052019B0061,emp008,2019-05-01 09:12:25,150000.0,KH6166700,20068542,2019-05-01,12:00:00,I08,1,AVENGERS: HỒI KẾT,ĐƠN,Thành viên,75000,Không

In [70]:
selected_columns = ['customerid', 'saledate', 'total']
rfm_df = dft_clean.loc[:, selected_columns]

In [71]:
rfm_df

       customerid            saledate     total
0      0000024994 2019-05-01 07:05:53  160000.0
1      0000024994 2019-05-01 07:06:45   75000.0
2       KH6166700 2019-05-01 07:15:58  225000.0
3       KH6166700 2019-05-01 07:17:28  150000.0
4       KH6166700 2019-05-01 07:26:28  160000.0
...           ...                 ...       ...
14593  0000029127 2019-05-31 20:37:02  135000.0
14594   KH6166700 2019-05-31 20:55:49   90000.0
14595   KH7965275 2019-05-31 21:26:50  180000.0
14596   KH6267491 2019-05-31 21:31:45  135000.0
14597  0001193386 2019-05-31 21:38:52   45000.0

[14598 rows x 3 columns]

In [72]:
rfm_df['customerid'].value_counts()

customerid
KH6166700     4043
0000029127    2854
0001121703     206
0003004563      19
KH3742976       18
              ...
0000040736       1
0001135173       1
0001012737       1
KH2504704        1
KH6267491        1
Name: count, Length: 4451, dtype: int64

### Select data

In [73]:
df = rfm_df.copy()

In [74]:

# Lấy ngày giao dịch gần nhất của tất cả khách hàng
latest_transaction_date_all_customers = df['saledate'].max()

# Tính Recency
df['recency'] = (latest_transaction_date_all_customers - df.groupby('customerid')['saledate'].transform('max')).dt.days

# Tính Frequency
df['frequency'] = df.groupby('customerid')['customerid'].transform('count')

# Tính Monetary
df['monetary'] = df.groupby('customerid')['total'].transform('sum')

# Hiển thị kết quả RFM
rfm_result = df[['customerid', 'recency', 'frequency', 'monetary']].drop_duplicates().reset_index(drop=True)
print(rfm_result)

      customerid  recency  frequency     monetary
0     0000024994        3          9     910000.0
1      KH6166700        0       4043  490635000.0
2     0001137446       30          6     975000.0
3     0001139169       30          3     825000.0
4      KH7065502       30          2     450000.0
...          ...      ...        ...          ...
4446  0001077482        0          1     180000.0
4447  0003008017        0          1     405000.0
4448   KH9143629        0          1     135000.0
4449   KH7965275        0          1     180000.0
4450   KH6267491        0          1     135000.0

[4451 rows x 4 columns]

In [75]:
df

,customerid,saledate,total,recency,frequency,monetary
0,0000024994,2019-05-01 07:05:53,160000.0,3,9,910000.0
1,0000024994,2019-05-01 07:06:45,75000.0,3,9,910000.0
2,KH6166700,2019-05-01 07:15:58,225000.0,0,4043,490635000.0
3,KH6166700,2019-05-01 07:17:28,150000.0,0,4043,490635000.0
4,KH6166700,2019-05-01 07:26:28,160000.0,0,4043,490635000.0
...,...,...,...,...,...,...
14593,0000029127,2019-05-31 20:37:02,135000.0,0,2854,330290000.0
14594,KH6166700,2019-05-31 20:55:49,90000.0,0,4043,490635000.0
14595,KH7965275,2019-05-31 21:26:50,180000.0,0,1,180000.0
14596,KH6267491,2019-05-31 21:31:45,135000.0,0,1,135000.0
14597,0001193386,2019-05-31 21:38:52,45000.0,0,4,225000.0

### Double check

In [76]:

print(df[df["customerid"] == "0001137446"], end = "\n\n")
print(df[df["customerid"] == "0001137446"]['total'].sum())

    customerid            saledate     total  recency  frequency  monetary
14  0001137446 2019-05-01 08:20:41  150000.0       30          6  975000.0
15  0001137446 2019-05-01 08:21:32   75000.0       30          6  975000.0
16  0001137446 2019-05-01 08:22:30  150000.0       30          6  975000.0
17  0001137446 2019-05-01 08:23:23  300000.0       30          6  975000.0
18  0001137446 2019-05-01 08:24:29  150000.0       30          6  975000.0
19  0001137446 2019-05-01 08:26:19  150000.0       30          6  975000.0

975000.0

In [77]:
rfm_result

      customerid  recency  frequency     monetary
0     0000024994        3          9     910000.0
1      KH6166700        0       4043  490635000.0
2     0001137446       30          6     975000.0
3     0001139169       30          3     825000.0
4      KH7065502       30          2     450000.0
...          ...      ...        ...          ...
4446  0001077482        0          1     180000.0
4447  0003008017        0          1     405000.0
4448   KH9143629        0          1     135000.0
4449   KH7965275        0          1     180000.0
4450   KH6267491        0          1     135000.0

[4451 rows x 4 columns]

### Tính RFM

In [78]:
rfm = rfm_result.copy()

In [79]:
# Tính R score
rfm['r_score'] = pd.cut(rfm['recency'], bins=3, labels=[3, 2, 1], include_lowest=True)

# Tính F score
rfm['f_score'] = pd.cut(rfm['frequency'], bins=3, labels=[1, 2, 3], include_lowest=True)

# Tính M score
rfm['m_score'] = pd.cut(rfm['monetary'], bins=3, labels=[1, 2, 3], include_lowest=True)

# Tính RFM cell
rfm['rfm_cell'] = rfm['r_score'].astype(str) + rfm['f_score'].astype(str) + rfm['m_score'].astype(str)

# Tính RFM score
rfm['rfm_score'] = rfm['r_score'].astype(int) + rfm['f_score'].astype(int) + rfm['m_score'].astype(int)

# Hiển thị kết quả
print(rfm[['customerid', 'r_score', 'f_score', 'm_score', 'rfm_cell', 'rfm_score']])

      customerid r_score f_score m_score rfm_cell  rfm_score
0     0000024994       3       1       1      311          5
1      KH6166700       3       3       3      333          9
2     0001137446       1       1       1      111          3
3     0001139169       1       1       1      111          3
4      KH7065502       1       1       1      111          3
...          ...     ...     ...     ...      ...        ...
4446  0001077482       3       1       1      311          5
4447  0003008017       3       1       1      311          5
4448   KH9143629       3       1       1      311          5
4449   KH7965275       3       1       1      311          5
4450   KH6267491       3       1       1      311          5

[4451 rows x 6 columns]

In [80]:
rfm

,customerid,recency,frequency,monetary,r_score,f_score,m_score,rfm_cell,rfm_score
0,0000024994,3,9,910000.0,3,1,1,311,5
1,KH6166700,0,4043,490635000.0,3,3,3,333,9
2,0001137446,30,6,975000.0,1,1,1,111,3
3,0001139169,30,3,825000.0,1,1,1,111,3
4,KH7065502,30,2,450000.0,1,1,1,111,3
...,...,...,...,...,...,...,...,...,...
4446,0001077482,0,1,180000.0,3,1,1,311,5
4447,0003008017,0,1,405000.0,3,1,1,311,5
4448,KH9143629,0,1,135000.0,3,1,1,311,5
4449,KH7965275,0,1,180000.0,3,1,1,311,5
4450,KH6267491,0,1,135000.0,3,1,1,311,5

In [81]:
rfm.to_csv("rfm.csv")